pal_fuel   = c("Geothermal" = "#6a3d9a",
               "Solar" = "#ff7f00",
               "Waste" = "#858585",
               "Wood" = "#8c613c",
               "Biomass" = "#8c613c",
               "Wind" = "#1f78b4",
               "Hydroelectric" = "#a6cee3",
               "Nuclear" = "#55a868",
               "Petroleum" = "#fdbf6f",
               "Crude Oil" = "#fdbf6f",
               "Petroleum Products" = "#eb8a19",
               # "Petroleum Products" = "#e59024",
               "Coal" = "#12253d",
               "Coal Coke" = "#848484",
               "Natural Gas" = "#c44e52",
               "Natural Gas (Dry)" = "#c44e52",
               "Natural Gas (Liquid)" = "#fb9a99",
               "Other Gases" = "#fb9a99",
               "Other Renewables" = "#a8a495",
               "Total Primary Energy" = "#fc8d62",
               "Total Petroleum" = "#383e56",
               "Total Fossil Fuels" = "#383e56",
               "Total Renewable Energy" = "#66c2a5",
               "Total Renewables" = "#66c2a5",
               "Electricity" = "#ff9f9b",
               "Total Energy" = "#8da0cb")

pal_sector   = c("Residential" = "#fd6968", 
                 "Commercial" = "#383e56", 
                 "Industrial" = "#9ecffd", 
                 "Transportation" = "#fbd55b", 
                 "Electric Power" = "#48be9d")

pal_type      = c('export' = '#3778bf',
                  'import' = '#feb308')

pal_shale     = c("Anadarko" = "#4aacae",
                  "Appalachia" = "#414e52",
                  "Bakken" = "#f6736a", 
                  "Eagle Ford" = "#eccd2f",  
                  "Haynesville" = "#6d7673", 
                  "Niobrara" = "#a0daf0", 
                  "Permian" = "#f5a273")
